// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Movie struct {
	ID    int     `json:"id"`
	Title string  `json:"title"`
	Year  string  `json:"year"`
	Stars []*Star `json:"stars"`
}

type NewMovie struct {
	Title string   `json:"title"`
	Year  string   `json:"year"`
	Stars []string `json:"stars"`
}

type Star struct {
	Name string `json:"name"`
}
