// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputMovie struct {
	ID    int          `json:"id"`
	Title string       `json:"title"`
	Year  string       `json:"year"`
	Stars []*InputStar `json:"stars"`
}

type InputStar struct {
	Name string `json:"name"`
}

type Movie struct {
	ID    int     `json:"id"`
	Title string  `json:"title"`
	Year  string  `json:"year"`
	Stars []*Star `json:"stars"`
}

type Star struct {
	Name string `json:"name"`
}
